[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "generate-docs"
requires-python = ">=3.9"
dynamic = ["version"]
dependencies = [
    'dbt-duckdb'
]

# Enables the usage of setuptools_scm
[tool.setuptools_scm]